services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.13.0
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/schema.yaml:/directus/schema.yaml
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      AUTH_PROVIDERS: "google"

      AUTH_GOOGLE_DRIVER: ${AUTH_GOOGLE_DRIVER}
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      AUTH_GOOGLE_ISSUER_URL: ${AUTH_GOOGLE_ISSUER_URL}
      AUTH_GOOGLE_SCOPE: ${AUTH_GOOGLE_SCOPE}
      AUTH_GOOGLE_IDENTIFIER_KEY: ${AUTH_GOOGLE_IDENTIFIER_KEY}
      AUTH_GOOGLE_ICON: ${AUTH_GOOGLE_ICON}
      AUTH_GOOGLE_LABEL: ${AUTH_GOOGLE_LABEL}
      AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_GOOGLE_REDIRECT_ALLOW_LIST: "http://localhost:8055/auth/google/callback"

      SESSION_COOKIE_DOMAIN: "localhost"
      SESSION_COOKIE_SAME_SITE: "lax"
      SESSION_COOKIE_SECURE: false

      PUBLIC_URL: ${PUBLIC_URL}
